{% set name = "aws-c-compression" %}
{% set version = "0.2.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 11d58a229e2961b2b36493155a981dea2c8a0bc0d113b0073deb8c3189cfa04e

build:
  number: 2
  run_exports:
    - {{ pin_subpackage("aws-c-compression", max_pin="x.x.x") }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - ninja
  host:
    - aws-c-common

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-compression${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/compression/compression.h  # [unix]
    - if not exist %LIBRARY_INC%\\aws\\compression\\compression.h exit 1          # [win]
    - if not exist %PREFIX%\\Library\\bin\\aws-c-compression.dll exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-compression
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C99 implementation of huffman encoding/decoding

extra:
  recipe-maintainers:
    - xhochy
